_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 106
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 106
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation_function:
    value: ReLU
batch_size:
    value: 32
classifier_layers:
    value: 2
dataset:
    value: CommonsenseQA
embedding_type:
    value: fasttext
learning_rate:
    value: 0.001
num_epochs:
    value: 100
optimizer:
    value: adam
rnn_architecture:
    value: lstm
