_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 106
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 106
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 256
dropout_rate:
    value: 0.2
embedding_dim:
    value: 300
epoch:
    value: 100
gradient_clipping:
    value: 1
hidden_dim:
    value: 64
label_smoothing:
    value: 0
max_lr:
    value: 0.001
model:
    value: qa_simple_classifier
weight_decay:
    value: 1e-05
