_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.12.8
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 64
dropout_rate:
    value: 0.3
embedding_dim:
    value: 300
epoch:
    value: 50
hidden_dim:
    value: 256
model:
    value: rnn
weight_decay:
    value: 1e-05
