_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 106
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 106
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.001
optimizer:
    value: adam
